### ISSUE TITLE
Adhere to abstract-level

### ISSUE THREAD

**Issue by shamilovtim** [greentriangle/react-native-leveldb#16]
In order for LevelDB implementations to be interchangeable across stacks and languages, the Level team created an abstract class that all Level implementations must implement. react-native-leveldb does not implement it, which means interop with leveldb plugins and the wider leveldb ecosystem is incomplete or broken. As a breaking change, we should align this repo to [abstract-level](https://github.com/Level/abstract-level) so that we can harness the full power of leveldb.

**Comment by savv** [comment]
Thanks @shamilovtim for your suggestion. The core library is meant to be a wrapper that is as close to the leveldb library itself, rather than abstract-level. It aims to be synchronous, which simplifies things a lot, and allows it to be super fast.

That said, we could make a wrapper for abstract. Would you be interested in doing this?

**Comment by shamilovtim** [comment]
@savv Yeah I am interested in doing it. I think I'd still use the synchronous methods, just implement the rest of the API.
